language: go

notifications:
  email: false

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  # LLVM 3.6
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
  - sudo apt-add-repository -y 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -y llvm-3.6-runtime libllvm3.6 llvm-3.6 llvm-3.6-dev

  # Download and build the source code of LLVM 3.6
  - mkdir -p $HOME/gopath/src/llvm.org/
  - wget -O $HOME/gopath/src/llvm.org/llvm-3.6.0.src.tar.xz http://llvm.org/releases/3.6.0/llvm-3.6.0.src.tar.xz
  - tar -C $HOME/gopath/src/llvm.org/ -xf $HOME/gopath/src/llvm.org/llvm-3.6.0.src.tar.xz
  - mv $HOME/gopath/src/llvm.org/llvm-3.6.0.src $HOME/gopath/src/llvm.org/llvm
  - sed -i 's/2.8.8/2.8.7/' $HOME/gopath/src/llvm.org/llvm/CMakeLists.txt
  - sed -i 's/2.8.8/2.8.7/' $HOME/gopath/src/llvm.org/llvm/docs/CMake.rst
  - $HOME/gopath/src/llvm.org/llvm/bindings/go/build.sh
  - go install llvm.org/llvm/bindings/go/llvm

  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get ./...

before_script:
  - wget https://gist.github.com/mewmew/379014c9a2e6885e238d/raw/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
