language: go

notifications:
  email: false

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  - mkdir -p $HOME/gopath/pkg/linux_amd64/llvm.org/llvm/bindings/go
  - wget -O $HOME/gopath/pkg/linux_amd64/llvm.org/llvm/bindings/go/llvm.a https://raw.githubusercontent.com/mewbuild/travis/master/linux_amd64/llvm.org/llvm/bindings/go/llvm.a
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get ./...

before_script:
  - wget https://gist.github.com/mewmew/379014c9a2e6885e238d/raw/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
